import {Injectable} from '@angular/core';


/* These are Nestlé's main brand names.  Some of their products have different individual names but most of them fall under these brand categories. The company is constantly buying and selling brands, however, so when in doubt, simply check the product's label.  Often, the Nestlé logo will not appear, but usually the Nestlé name can be found in the fine print. */
@Injectable()
export class BrandData {
  data: any;
  owners: any;

  constructor() {
    this.data = [
      {name: "Aberfoyle", owner: 0},
      {name: "Acqua Panna", owner: 0},
      {name: "Al Manhal", owner: 0},
      {name: "Aquarel", owner: 0},
      {name: "Arrowhead", owner: 0},
      {name: "Bonka", owner: 0},
      {name: "Carnation", owner: 0},
      {name: "Coffee Crisp", owner: 0},
      {name: "Contrex", owner: 0},
      {name: "Deer Park", owner: 0},
      {name: "Evian", owner: 0},
      {name: "Gerber", owner: 0},
      {name: "Gerber Graduates", owner: 0},
      {name: "Hepar", owner: 0},
      {name: "KitKat", owner: 0},
      {name: "Kit Kat", owner: 0},
      {name: "La Vie", owner: 0},
      {name: "Levissima", owner: 0},
      {name: "Libby's", owner: 0},
      {name: "Loumidis", owner: 0},
      {name: "Milo", owner: 0},
      {name: "Montclair", owner: 0},
      {name: "Nescafé", owner: 0},
      {name: "Nescau", owner: 0},
      {name: "Nespresso", owner: 0},
      {name: "Nesquik", owner: 0},
      {name: "Nestea", owner: 0, notes: "Partership with Coca-Cola"},
      {name: "Ozarka", owner: 0},
      {name: "Perrier", owner: 0},
      {name: "Poland Spring", owner: 0},
      {name: "PURE LIFE", owner: 0},
      {name: "Ricore", owner: 0},
      {name: "Ricoffy", owner: 0},
      {name: "San Pellegrino", owner: 0},
      {name: "S. Pellegrino", owner: 0},
      {name: "Santa Maria", owner: 0},
      {name: "Vera", owner: 0},
      {name: "Viladrau", owner: 0},
      {name: "Vittel", owner: 0},
      {name: "Zoégas", owner: 0},
      {name: "Caro", owner: 0},
      {name: "Nido", owner: 0},
      {name: "Nespray", owner: 0},
      {name: "Ninho", owner: 0},
      {name: "Milkmaid", owner: 0},
      {name: "La Lechera", owner: 0},
      {name: "Moca", owner: 0},
      {name: "Klim", owner: 0},
      {name: "Gloria", owner: 0},
      {name: "Svelty", owner: 0},
      {name: "Molico", owner: 0},
      {name: "Nestlé Omega Plus", owner: 0},
      {name: "Bear Brand", owner: 0},
      {name: "Coffee-mate", owner: 0},
      {name: "LC1", owner: 0},
      {name: "Chmyto", owner: 0},
      {name: "La Laitiere", owner: 0},
      {name: "Sveltesse", owner: 0},
      {name: "Yoco", owner: 0},
      {name: "Nestlé Quik", owner: 0},
      {name: "Good Start", owner: 0},
      {name: "SMA", owner: 0},
      {name: "Follow-Up", owner: 0},
      {name: "Follow-Up Soy", owner: 0},
      {name: "Alsoy", owner: 0},
      {name: "Nursoy", owner: 0},
      {name: "Nan", owner: 0},
      {name: "Lactogen", owner: 0},
      {name: "Beba", owner: 0},
      {name: "Nestogen", owner: 0},
      {name: "Cérélac", owner: 0},
      {name: "Neslac", owner: 0},
      {name: "Nestum", owner: 0},
      {name: "Guigoz", owner: 0},
      {name: "PowerBar", owner: 0},
      {name: "Nutren", owner: 0},
      {name: "Peptamen", owner: 0},
      {name: "Modulen", owner: 0},
      {name: "Maggi", owner: 0},
      {name: "Buitoni", owner: 0},
      {name: "Winiary", owner: 0},
      {name: "Stouffer's", owner: 0},
      {name: "Hot Pockets", owner: 0},
      {name: "Frisco", owner: 0},
      {name: "Motta", owner: 0},
      {name: "Camy", owner: 0},
      {name: "Savory", owner: 0},
      {name: "Peters", owner: 0},
      {name: "Haagen Dasz", owner: 0},
      {name: "Movenpick", owner: 0},
      {name: "Herta", owner: 0},
      {name: "Toll House", owner: 0},
      {name: "Crunch", owner: 0},
      {name: "Cailler", owner: 0},
      {name: "Galak", owner: 0},
      {name: "Milkybar", owner: 0},
      {name: "Milky bar", owner: 0},
      {name: "Quality Street", owner: 0},
      {name: "Smarties", owner: 0, notes: "Outside the USA"},
      {name: "Baci", owner: 0},
      {name: "After Eight", owner: 0},
      {name: "Baby Ruth", owner: 0},
      {name: "Butterfinger", owner: 0},
      {name: "Lion", owner: 0},
      {name: "Aero", owner: 0},
      {name: "Polo", owner: 0},
      {name: "Frutips", owner: 0},
      {name: "Chef", owner: 0},
      {name: "Davigel", owner: 0},
      {name: "Minor's", owner: 0},
      {name: "Santa Rica", owner: 0},
      {name: "Friskies", owner: 0},
      {name: "Fancy Feast", owner: 0},
      {name: "Alpo", owner: 0},
      {name: "Mighty Dog", owner: 0},
      {name: "Gourmet", owner: 0},
      {name: "Mon Petit", owner: 0},
      {name: "Felix", owner: 0},
      {name: "Purina Dog Chow", owner: 0},
      {name: "Pro Plan", owner: 0},
      {name: "ONE", owner: 0},
      {name: "Beneful", owner: 0},
      {name: "Tidy Cats", owner: 0},
      {name: "Alcon", owner: 0},
      {name: "Galderma", owner: 0},
      {name: "L'Oréal", owner: 0},
      {name: "Laboratoires Innéov", owner: 0},
      {name: "Maybelline", owner: 0},
      {name: "Garnier", owner: 0},
      {name: "Lancôme", owner: 0},
      {name: "Biotherm", owner: 0},
      {name: "Ralph Lauren", owner: 0},
      {name: "Giorgio Armani", owner: 0},
      {name: "Matrix", owner: 0},
      {name: "Redken", owner: 0},
      {name: "Gerber Childrenswear", owner: 0},
      {name: "Gerber Life Insurance Company", owner: 0},
      {name: "Gold Blend", owner: 0},
      {name: "Blend 37", owner: 0},
      {name: "Alta Rica", owner: 0},
      {name: "Cap Colombie", owner: 0},
      {name: "Cappuccino", owner: 0},
      {name: "Decaff", owner: 0},
      {name: "Fine Blend", owner: 0},
      {name: "Chambourcy", owner: 0},
      {name: "Coffee-Mate", owner: 0},
      {name: "Coffee Mate", owner: 0},
      {name: "CoffeeMate", owner: 0},
      {name: "Fussells", owner: 0},
      {name: "Ideal", owner: 0},
      {name: "Tip-Top", owner: 0},
      {name: "Tip Top", owner: 0},
      {name: "TipTop", owner: 0},
      {name: "Bonjour", owner: 0},
      {name: "Chamby", owner: 0},
      {name: "Creme Vienna", owner: 0},
      {name: "Darlky", owner: 0},
      {name: "Flanby", owner: 0},
      {name: "Fulcreem Custard", owner: 0},
      {name: "Hippopota", owner: 0},
      {name: "Jacky", owner: 0},
      {name: "Dremly", owner: 0},
      {name: "Le Grande", owner: 0},
      {name: "Nouvelle", owner: 0},
      {name: "Rowntree", owner: 0},
      {name: "After Eights", owner: 0},
      {name: "Lyons Maid", owner: 0},
      {name: "Animal Bar", owner: 0},
      {name: "Baci Chocolate", owner: 0},
      {name: "Black Magic", owner: 0},
      {name: "Blue Riband", owner: 0},
      {name: "Breakaway", owner: 0},
      {name: "Cabana", owner: 0},
      {name: "Caramac", owner: 0},
      {name: "Caramel Wafer", owner: 0},
      {name: "Cello", owner: 0},
      {name: "Creamola", owner: 0},
      {name: "Dairy Crunch", owner: 0},
      {name: "Drifter", owner: 0},
      {name: "Eclipse", owner: 0},
      {name: "Good News", owner: 0},
      {name: "Festival", owner: 0},
      {name: "Fruit Pastilles", owner: 0},
      {name: "Fox's Glacier Mints", owner: 0},
      {name: "Gray & Dunn", owner: 0},
      {name: "Henri Nestlé collection", owner: 0},
      {name: "Jellytots", owner: 0},
      {name: "Karima", owner: 0},
      {name: "Matchmakers", owner: 0},
      {name: "Montego", owner: 0},
      {name: "Muchies", owner: 0},
      {name: "Novo", owner: 0},
      {name: "Rolo", owner: 0},
      {name: "RPC", owner: 0},
      {name: "Savana", owner: 0},
      {name: "Secret", owner: 0},
      {name: "Toffee Crisp", owner: 0},
      {name: "Toffo", owner: 0},
      {name: "Tooty Frooties", owner: 0},
      {name: "Walnut Whip", owner: 0},
      {name: "Weekend", owner: 0},
      {name: "Yorkie", owner: 0},
      {name: "Care contact lens", owner: 0},
      {name: "Alcon contact lens", owner: 0},
      {name: "British Shoyu", owner: 0},
      {name: "British vinegars", owner: 0},
      {name: "Cook-in-the-Pot", owner: 0},
      {name: "Dufrais", owner: 0},
      {name: "Sarsons", owner: 0},
      {name: "Ashbourne", owner: 0},
      {name: "Contrexèville", owner: 0},
      {name: "Buxton", owner: 0},
      {name: "Bittelloise", owner: 0},
      {name: "Build-up", owner: 0},
      {name: "Build up", owner: 0},
      {name: "Buildup", owner: 0},
      {name: "Elevenses", owner: 0},
      {name: "Flo-Mix", owner: 0},
      {name: "Libby's C Drinks", owner: 0},
      {name: "Mix-O-Choc", owner: 0},
      {name: "Mix O Choc", owner: 0},
      {name: "MixOChoc", owner: 0},
      {name: "Moonshine", owner: 0},
      {name: "Nescoré", owner: 0},
      {name: "Nesfit", owner: 0},
      {name: "Nescoré", owner: 0},
      {name: "Slender", owner: 0},
      {name: "Superquik", owner: 0},
      {name: "Um Bongo", owner: 0},
      {name: "Findus", owner: 0},
      {name: "Crosse & Blackwell", owner: 0},
      {name: "Alphabetti", owner: 0},
      {name: "Bonne Cuisine", owner: 0},
      {name: "Dish of the Day", owner: 0},
      {name: "Eskimo", owner: 0},
      {name: "Four Seasons", owner: 0},
      {name: "Healthy Balance", owner: 0},
      {name: "Lean Cuisine", owner: 0},
      {name: "Pasta choice", owner: 0},
      {name: "Rice & Things", owner: 0},
      {name: "Scrunchies", owner: 0},
      {name: "Waistline", owner: 0},
      {name: "Branston Pickle", owner: 0},
      {name: "Gales honey", owner: 0},
      {name: "Holgates honey", owner: 0},
      {name: "Pan Yan", owner: 0},
      {name: "Sun-Pat", owner: 0},
      {name: "Vessen paté", owner: 0},
      {name: "Tartex", owner: 0},
      {name: "Shredded Wheat", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Shreddies", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Cheerios", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Cinnamon Toast Crunch", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Cocoa Puffs", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Crisp Rice", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Energen", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Force", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Golden Grahams", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Honey Nut Cheerios", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Lucky Charms", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Robertson's cornflakes", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Sunny Jim", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Wheatflakes", owner: 0, notes: "Outside the USA and Canada."},
      {name: "Claudel", owner: 0},
      {name: "Go-Cat", owner: 0},
      {name: "Go-Dog", owner: 0},
      {name: "Albers", owner: 0},
      {name: "Additions", owner: 0, notes: "Nutrition Supplement"},
      {name: "100 Grand", owner: 0},
      {name: "BitOHoney", owner: 0},
      {name: "Bit-O-Honey", owner: 0},
      {name: "Bit O Honey", owner: 0},
      {name: "ChefMate", owner: 0},
      {name: "Chef-Mate", owner: 0},
      {name: "Chef Mate", owner: 0},
      {name: "Chunky", owner: 0},
      {name: "Condimix", owner: 0},
      {name: "David & Sons", owner: 0, notes: "sunflower seeds"},
      {name: "European Style", owner: 0},
      {name: "Flipz", owner: 0},
      {name: "Fun Dip", owner: 0, notes: "nutrition supplement"},
      {name: "Glytrol", owner: 0},
      {name: "Goobers", owner: 0},
      {name: "Icecap", owner: 0},
      {name: "Jim Dandy", owner: 0},
      {name: "Kathryn Beich", owner: 0},
      {name: "Lik-M-Aid", owner: 0},
      {name: "Nestlé Buncha Crunch", owner: 0},
      {name: "Nestlé Crunch", owner: 0},
      {name: "Nips", owner: 0},
      {name: "Oh Henry", owner: 0},
      {name: "Ortega", owner: 0},
      {name: "Pearson's Nips", owner: 0},
      {name: "Perugina", owner: 0},
      {name: "Perugina Baci", owner: 0},
      {name: "Perugina Gianduia", owner: 0},
      {name: "Perugina Ore Liete", owner: 0},
      {name: "Peter's Semi-sweet Chocolates", owner: 0},
      {name: "Pixy Stix", owner: 0},
      {name: "Probalance", owner: 0},
      {name: "Crucial", owner: 0},
      {name: "Trio", owner: 0},
      {name: "Trio Supreme", owner: 0},
      {name: "Turtles", owner: 0},
      {name: "Que Bueno!", owner: 0},
      {name: "Raisinets", owner: 0},
      {name: "SnoCaps", owner: 0},
      {name: "Sno-Caps", owner: 0},
      {name: "Sno Caps", owner: 0},
      {name: "Taster's Choice", owner: 0},
      {name: "Treasures", owner: 0},
      {name: "Trio", owner: 0},
      {name: "Willy Wonka's", owner: 0},
      {name: "Willy Wonka's Gobstoppers", owner: 0},
      {name: "Willy Wonka's Nerds", owner: 0},
      {name: "Willy Wonka's Runts", owner: 0},
      {name: "Willy Wonka's Sweetarts", owner: 0},

      {name: "Axe", owner: 1},
      {name: "Lynx", owner: 1},
      {name: "Blue Band", owner: 1},
      {name: "Dermalogica", owner: 1},
      {name: "Dove", owner: 1},
      {name: "Flora", owner: 1},
      {name: "Becel", owner: 1},
      {name: "Heartbrand", owner: 1},
      {name: "Hellmann's", owner: 1},
      {name: "Best Foods", owner: 1},
      {name: "Knorr", owner: 1},
      {name: "Lipton", owner: 1, notes: "Partnership with Pepsico"},
      {name: "Lux", owner: 1},
      {name: "Magnum", owner: 1},
      {name: "Rexona", owner: 1},
      {name: "Omo", owner: 1},
      {name: "Sure", owner: 1},
      {name: "Degree", owner: 1},
      {name: "Shield", owner: 1},
      {name: "Surf", owner: 1},
      {name: "Sunsilk", owner: 1},
      {name: "Trio", owner: 1},

      {name: "Pepsi", owner: 2},
      {name: "Mountain Dew", owner: 2},
      {name: "Lay's", owner: 2},
      {name: "Gatorade", owner: 2},
      {name: "Tropicana", owner: 2},
      {name: "7 Up", owner: 2, notes: "Outside the USA"},
      {name: "Doritos", owner: 2},
      {name: "Quaker", owner: 2},
      {name: "Cheetos", owner: 2},
      {name: "Mirinda", owner: 2},
      {name: "Ruffles", owner: 2},
      {name: "Aquafina", owner: 2},
      {name: "Tostitos", owner: 2},
      {name: "Mist Twist", owner: 2},
      {name: "Fritos", owner: 2},
      {name: "Walkers potato crisps", owner: 2},

      {name: "Coke", owner: 3},
      {name: "Minute Maid", owner: 3},
      {name: "Dasani", owner: 3},
      {name: "Powerade", owner: 3},
      {name: "Dr Pepper", owner: 3},
      {name: "Dr. Pepper", owner: 3},
      {name: "Orange Crush", owner: 3},
      {name: "Vitamin Water", owner: 3},
      {name: "Tab Energy", owner: 3},
      {name: "Schweppes", owner: 3},
      {name: "Fanta", owner: 3},
      {name: "Barq's", owner: 3},
      {name: "Odwalla", owner: 3},
      {name: "Fruitopia", owner: 3},
      {name: "Brazzi", owner: 3},
      {name: "Dannon", owner: 3},
      {name: "Danone", owner: 3},
      {name: "Rockstar", owner: 3},
    ];

    this.owners = [
      {name: "Nestlé"},
      {name: "Unilever"},
      {name: "Pepsico"},
      {name: "Coca-Cola"}
    ]

  }

  getOwner(brandName) {
    if (brandName) {
      for (var i = 0; i < this.data.length; i++) {
        if (brandName.localeCompare(this.data[i].name, 'en', {sensitivity: 'base'}) == 0) {
          var brand = this.data[i];
          brand.owner = this.owners[brand.owner];
          return brand;
        }
      }
    }
    return null;
  }

}
