import {Injectable} from '@angular/core';


/* These are Nestlé's main brand names.  Some of their products have different individual names but most of them fall under these brand categories. The company is constantly buying and selling brands, however, so when in doubt, simply check the product's label.  Often, the Nestlé logo will not appear, but usually the Nestlé name can be found in the fine print. */
@Injectable()
export class BrandData {
  data: any;

  constructor() {
    // TODO this should give typing suggestions in app
    this.data = [
      {name: "Aberfoyle", owner: "Nestlé"},
      {name: "Acqua Panna", owner: "Nestlé"},
      {name: "Al Manhal", owner: "Nestlé"},
      {name: "Aquarel", owner: "Nestlé"},
      {name: "Arrowhead", owner: "Nestlé"},
      {name: "Bonka", owner: "Nestlé"},
      {name: "Carnation", owner: "Nestlé"},
      {name: "Contrex", owner: "Nestlé"},
      {name: "Deer Park", owner: "Nestlé"},
      {name: "Evian", owner: "Nestlé"},
      {name: "Gerber", owner: "Nestlé"},
      {name: "Gerber Graduates", owner: "Nestlé"},
      {name: "Hepar", owner: "Nestlé"},
      {name: "La Vie", owner: "Nestlé"},
      {name: "Levissima", owner: "Nestlé"},
      {name: "Libby's", owner: "Nestlé"},
      {name: "Loumidis", owner: "Nestlé"},
      {name: "Milo", owner: "Nestlé"},
      {name: "Montclair", owner: "Nestlé"},
      {name: "Nescafé", owner: "Nestlé"},
      {name: "Nescau", owner: "Nestlé"},
      {name: "Nespresso", owner: "Nestlé"},
      {name: "Nesquik", owner: "Nestlé"},
      {name: "Nestea", owner: "Nestlé"},
      {name: "Ozarka", owner: "Nestlé"},
      {name: "Perrier", owner: "Nestlé"},
      {name: "Poland Spring", owner: "Nestlé"},
      {name: "PURE LIFE", owner: "Nestlé"},
      {name: "Ricore", owner: "Nestlé"},
      {name: "Ricoffy", owner: "Nestlé"},
      {name: "S. Pellegrino", owner: "Nestlé"},
      {name: "Santa Maria", owner: "Nestlé"},
      {name: "Vera", owner: "Nestlé"},
      {name: "Viladrau", owner: "Nestlé"},
      {name: "Vittel", owner: "Nestlé"},
      {name: "Zoégas", owner: "Nestlé"},

      {name: "Caro", owner: "Nestlé"},
      {name: "Nido", owner: "Nestlé"},
      {name: "Nespray", owner: "Nestlé"},
      {name: "Ninho", owner: "Nestlé"},
      {name: "Carnation", owner: "Nestlé"},
      {name: "Milkmaid", owner: "Nestlé"},
      {name: "La Lechera", owner: "Nestlé"},
      {name: "Moca", owner: "Nestlé"},
      {name: "Klim", owner: "Nestlé"},
      {name: "Gloria", owner: "Nestlé"},
      {name: "Svelty", owner: "Nestlé"},
      {name: "Molico", owner: "Nestlé"},
      {name: "Nestlé Omega Plus", owner: "Nestlé"},
      {name: "Bear Brand", owner: "Nestlé"},
      {name: "Coffee-mate", owner: "Nestlé"},
      {name: "LC1", owner: "Nestlé"},
      {name: "Chmyto", owner: "Nestlé"},
      {name: "La Laitiere", owner: "Nestlé"},
      {name: "Sveltesse", owner: "Nestlé"},
      {name: "Yoco", owner: "Nestlé"},
      {name: "Nestlé Quik", owner: "Nestlé"},
      {name: "Good Start", owner: "Nestlé"},
      {name: "SMA", owner: "Nestlé"},
      {name: "Follow-Up", owner: "Nestlé"},
      {name: "Follow-Up Soy", owner: "Nestlé"},
      {name: "Alsoy", owner: "Nestlé"},
      {name: "Nursoy", owner: "Nestlé"},
      {name: "Nan", owner: "Nestlé"},
      {name: "Lactogen", owner: "Nestlé"},
      {name: "Beba", owner: "Nestlé"},
      {name: "Nestogen", owner: "Nestlé"},
      {name: "Cérélac", owner: "Nestlé"},
      {name: "Neslac", owner: "Nestlé"},
      {name: "Nestum", owner: "Nestlé"},
      {name: "Guigoz", owner: "Nestlé"},
      {name: "PowerBar", owner: "Nestlé"},
      {name: "Nutren", owner: "Nestlé"},
      {name: "Peptamen", owner: "Nestlé"},
      {name: "Modulen", owner: "Nestlé"},
      {name: "Maggi", owner: "Nestlé"},
      {name: "Buitoni", owner: "Nestlé"},
      {name: "Winiary", owner: "Nestlé"},
      {name: "Stouffer's", owner: "Nestlé"},
      {name: "Hot Pockets", owner: "Nestlé"},
      {name: "Frisco", owner: "Nestlé"},
      {name: "Motta", owner: "Nestlé"},
      {name: "Camy", owner: "Nestlé"},
      {name: "Savory", owner: "Nestlé"},
      {name: "Peters", owner: "Nestlé"},
      {name: "Haagen Dasz", owner: "Nestlé"},
      {name: "Movenpick", owner: "Nestlé"},
      {name: "Herta", owner: "Nestlé"},
      {name: "Toll House", owner: "Nestlé"},
      {name: "Crunch", owner: "Nestlé"},
      {name: "Cailler", owner: "Nestlé"},
      {name: "Galak", owner: "Nestlé"},
      {name: "Milkybar", owner: "Nestlé"},
      {name: "KitKat", owner: "Nestlé"},
      {name: "Quality Street", owner: "Nestlé"},
      {name: "Smarties", owner: "Nestlé"},
      {name: "Baci", owner: "Nestlé"},
      {name: "After Eight", owner: "Nestlé"},
      {name: "Baby Ruth", owner: "Nestlé"},
      {name: "Butterfinger", owner: "Nestlé"},
      {name: "Lion", owner: "Nestlé"},
      {name: "Aero", owner: "Nestlé"},
      {name: "Polo", owner: "Nestlé"},
      {name: "Frutips", owner: "Nestlé"},
      {name: "Chef", owner: "Nestlé"},
      {name: "Davigel", owner: "Nestlé"},
      {name: "Minor's", owner: "Nestlé"},
      {name: "Santa Rica", owner: "Nestlé"},
      {name: "Friskies", owner: "Nestlé"},
      {name: "Fancy Feast", owner: "Nestlé"},
      {name: "Alpo", owner: "Nestlé"},
      {name: "Mighty Dog", owner: "Nestlé"},
      {name: "Gourmet", owner: "Nestlé"},
      {name: "Mon Petit", owner: "Nestlé"},
      {name: "Felix", owner: "Nestlé"},
      {name: "Purina Dog Chow", owner: "Nestlé"},
      {name: "Pro Plan", owner: "Nestlé"},
      {name: "ONE", owner: "Nestlé"},
      {name: "Beneful", owner: "Nestlé"},
      {name: "Tidy Cats", owner: "Nestlé"},
      {name: "Alcon", owner: "Nestlé"},
      {name: "Galderma", owner: "Nestlé"},
      {name: "L'Oréal", owner: "Nestlé"},
      {name: "Laboratoires Innéov", owner: "Nestlé"},
      {name: "Maybelline", owner: "Nestlé"},
      {name: "Garnier", owner: "Nestlé"},
      {name: "Lancôme", owner: "Nestlé"},
      {name: "Biotherm", owner: "Nestlé"},
      {name: "Ralph Lauren", owner: "Nestlé"},
      {name: "Giorgio Armani", owner: "Nestlé"},
      {name: "Matrix", owner: "Nestlé"},
      {name: "Redken", owner: "Nestlé"},
      {name: "Gerber Childrenswear", owner: "Nestlé"},
      {name: "Gerber Life Insurance Company", owner: "Nestlé"}
    ];
  }

  getOwner(brandName) {
    var brand = null;
    for (var i = 0; i < this.data.length; i++) {
      if (brandName.localeCompare(this.data[i].name, 'en', { sensitivity: 'base' }) == 0) {
        brand = this.data[i];
        break;
      }
    }
    return brand;
  }

}
